### ISSUE TITLE
General Package Structure

### ISSUE THREAD

**Issue by metaloph1l** [metaloph1l/pacman#2]
Create the general package structure for client, server, model, etc.

**Comment by lanoxx** [comment]
I think the package structure should be a little different. You have created too many sub packages which seems like a little overkill (also see my domain branch).

I propose a structure as following:

Base Package: at.ac.tuwien.foop.pacman
Then we create the packages:
- domain (with business logic and domain classes such as Pacman, Player, Square, etc.)
- application (Controller classes which handle the network communication and the game protocoll and also RMI stuff)
- ui (The Java Swing Classes and Program initialization logic)

As such I would also move the gameserver and client packages to the application package.
In the ui package I would create the following classes:

ui.StartUpClient (main for client)
ui.StartUpGameServer (main for server)

**Comment by lanoxx** [comment]
An update is for my suggested package structure is in the domain branch now.
